matrix:
  include:
    - addons:
        apt:
          packages:
            - gcc
    - addons:
        apt:
          packages:
            - clang
sudo: false
language: python
python:
- "2.7"
addons:
    apt:
        packages:
            - make
            - python-virtualenv
            - unzip
before_script:
- "cd .."
# make virtual env
- "python /usr/lib/python2.7/dist-packages/virtualenv.py virtualenv;"
- "cd virtualenv;"
- "source bin/activate;"
# install tcc
- "git clone http://repo.or.cz/tinycc.git tinycc && cd tinycc && git checkout d5e22108a0dc48899e44a158f91d5b3215eb7fe6"
- "./configure --disable-static --tccdir=./ --libdir=$(pwd) --includedir=$(pwd)"
- "make && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd);cd ..;"
- "cp tinycc/libtcc.h include"
- "cp tinycc/libtcc.so.1.0 tinycc/libtcc.so"
# install elfesteem
- "git clone https://github.com/serpilliere/elfesteem elfesteem && cd elfesteem && python setup.py install && cd ..;"
# install pyparsing
- "pip install pyparsing"
# install z3 with a known to working version
- "wget https://github.com/serpilliere/z3-prebuild/raw/master/z3.tgz"
- "tar xzf z3.tgz"
- "cd z3/build"
- "make install"
- "cd ../.."
# install miasm
- "cd ..;"
- "cd miasm;"
- "python setup.py build build_ext -I$(pwd)/../virtualenv/include -L$(pwd)/../virtualenv/tinycc"
- "python setup.py install"
script: "python -c 'import z3; x = z3.BitVec(chr(0x41), 32)' && cd test && python test_all.py"
