matrix:
  include:
    - os: osx
      language: generic
      python: 2.7
before_script:
- "cd .."
# make virtual env
- "virtualenv virtualenv;"
- "cd virtualenv;"
- "source bin/activate;"
# install elfesteem
- "git clone https://github.com/serpilliere/elfesteem elfesteem && cd elfesteem && python setup.py install && cd ..;"
# install pyparsing
- "pip install pyparsing"
# install miasm
- "cd ..;"
- "cd miasm;"
- "python setup.py build build_ext -I$(pwd)/../virtualenv/include -L$(pwd)/../virtualenv/tinycc"
- "python setup.py install"
script: "cd test && python test_all.py"
